name: wemo_calibration

channels:
  - default
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib=3.4.3
  - pandas=1.3.3
  - numpy=1.20.3
  - pyproj=3.1.0
  - scipy=1.6.3
  - cartopy=0.18.0 
  - netcdf4=1.5.6
  - xarray=0.19.0
  - dask=2021.9.0
  - tqdm=4.62.3
  - jupyterlab=3.1.12
  - jupyter_contrib_nbextensions=0.5.1
  - pip
  - pip: 
    - argparse==1.4.0